### PR TITLE
TinyIoC NuGet package updated to version 1.3 and TinyIoC made internal

### LINKED ISSUE #60: TinyIoC should not be public in TinyIoC namespace
Currently Chill depends on TinyIoC which is public and in `TinyIoC` namespace. That makes it incompatible with any other project that has TinyIoC public in `TinyIoC` namespace (which is how the TinyIoC package is installed without manual changes).

### PR DESCRIPTION
**Pull request by IharBury**
Resolves #60

### CODE REVIEW

**Comment by IharBury** [comment]
@Erwinvandervalk, @dennisdoomen, we need this change to be able to use Chill in GisVision.Middleware. Can you review/merge/release it, please?

**Comment by IharBury** [comment]
@dennisdoomen Can you also tag the release, please?

**Comment by dennisdoomen** [comment]
Do you see this as a breaking change?

**Comment by IharBury** [comment]
I see it as a breaking change for those who used TinyIoC container from Chill in their specs.

**Comment by dennisdoomen** [comment]
@Erwinvandervalk what about you?

**Comment by Erwinvandervalk** [comment]
Yeah.. it's breaking because people might not expect this behavior..

**Pull request merged**
