### PR TITLE
Async givens and whens are executed in the default synchronization context

### PR DESCRIPTION
**Pull request by IharBury**
It does not make sense to queue a task to a worker thread, that will do blocking waiting, and to do blocking waiting for the queued task. That just blocks one more thread and can lead to problems for other tasks requiring worker threads.

### CODE REVIEW

**Comment by dennisdoomen** [comment]
Actually, I've found this to be the only way to prevent deadlocks when synchronously waiting for a Task.

**Comment by IharBury** [comment]
Waiting on another thread can theoretically solve deadlock caused by using synchronization context that has concurrency limitations. In that case Task.Run will run in the default synchronization context without those limitations. However, we are talking about tests. They should have the default synchronization context in the first place. And writing deadlocking code is not a good idea in the first place. `Task.ConfigureAwait(false)` should be used by the async libraries which don't need to run async continuations in the same synchronization context.

**Comment by dennisdoomen** [comment]
Regardless, having Chill deadlock on AppVeyor because the code involves doesn't use `ConfigureAwait` correctly is not a smart thing to do.

**Comment by IharBury** [comment]
But to get a deadlock the test should be executed in a synchronization context that has concurrency limitations. Where can such a context come from in tests?

**Comment by dennisdoomen** [comment]
AppVeyor used to use single-core build agent. That's where I detected this. I even had to have an AppVeyor engineer assist me with that.

**Comment by IharBury** [comment]
I still don't see how this can be related to the number of cores. Task continuations run on worker threads in the default synchronization context. And threads can run concurrently even on single core processors.

**Comment by IharBury** [comment]
However, by investigating further I found that xunit can have problems with async tests (for example, discussed here https://github.com/xunit/xunit/issues/864) because it tries to create its own synchronization context with some advanced features. Looks like their design is not quite solid there.

**Comment by IharBury** [comment]
I've changed the code to execute async givens and whens in the default synchronization context. This should fix deadlocks in xUnit by running continuations in givens and whens also in the default synchronization context.

**Pull request merged**
